config/routes.rb
Rails.application.routes.draw do
 
  
  

  resources :courses
  devise_for :teachers
  get '/course_list'=> 'welcome_teacher#course_list'
   get '/create_course' => 'courses#new'
  get '/teacher' => 'welcome_teacher#index'
   get '/user' => 'welcome#index'
   post 'subscribe' => 'courses#subscribe'
  devise_for :users
  root 'welcome#index'

end

app/models/course.rb
class Course < ActiveRecord::Base

has_many :subscriptions
has_many :users,through: :subscriptions

has_many :teacher_course_mappings
has_many :teachers,through: :teacher_course_mappings

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :User
  belongs_to :Course
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable, :lockable

  has_many :teacher_course_mappings
  has_many :courses,through: :teacher_course_mappings       
end

app/models/teacher_course_mapping.rb
class TeacherCourseMapping < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :course
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable, :lockable


  has_many :subscriptions
  has_many :courses,through: :subscriptions       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :is_subscribed
  def is_subscribed(course_id)

  	@val=Subscription.find_by_User_id_and_Course_id(current_user.id,course_id)
  end	


   
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  
  #before_action :authenticate_teacher!
  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end
  
  # GET /courses/new
  def new
    @course = Course.new
  end
   
  def subscribe
    course_id=params[:course_id];
   if !is_subscribed(course_id)
    Subscription.create(User_id:current_user.id,Course_id:course_id)
  else
    #Subscription.destroy(User_id:current_user.id,Course_id:course_id)
    Subscription.find_by_User_id_and_Course_id(current_user.id,course_id).destroy

   end
  return redirect_to '/'
  end  
  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    
    respond_to do |format|
      if @course.save
        if current_teacher!=nil
        tcm=TeacherCourseMapping.create(Teacher_id: current_teacher.id,Course_id: @course.id)
        end
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:title, :description,:content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	 before_action :authenticate_user!
  def index
  	@courses=Course.all
  end
  
end

app/controllers/welcome_teacher_controller.rb
class WelcomeTeacherController < ApplicationController
	 before_action :authenticate_teacher!
  def index
  end

  def course_list
    @courses=current_teacher.courses.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/welcome_teacher_helper.rb
module WelcomeTeacherHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
   <div class="field">
    <%= f.label :Content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Courses</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>
 <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.title %></td>
        <td><%= course.description %></td>
        <td><%= course.content %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
</tbody>
  
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @course.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course.description %>
</p>
<p>
  <strong>Content:</strong>
  <%= @course.content %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coursera</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/teachers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_teacher_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_teacher_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_teacher_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_teacher_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>
<%= link_to "Students Login ?", user_path, :class => 'navbar-link'  %> 
<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<%= link_to "Teachers Login ?", teacher_path, :class => 'navbar-link'  %> |

<h1>Here are the list of available courses</h1>
<% @courses.each do |course| %>
    <br>
      <tr>
        <td><%= course.title %></td><br>
        <td><%= course.description %></td><br>
     <% if current_user!=nil and is_subscribed(course.id) %>
        <td><%= course.content %></td>
    <% end %>   
        <td><%= link_to 'Show', course %></td>
        <%= link_to "Subscribe", url_for(controller: :courses, action: :subscribe, course_id: course.id), method: :post %>
      </tr>
    <% end %>

app/views/welcome_teacher/course_list.html.erb
<tbody>
<h1>Here i have to view thw course list</h1>
    <% @courses.each do |course| %>
    <br>
      <tr>
        <td><%= course.title %></td>
        <td><%= course.description %></td>
        <td><%= course.content %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

app/views/welcome_teacher/index.html.erb
<h1>Hello, Teacher!</h1>
<% if teacher_signed_in? %>
  Logged in as <strong><%= current_teacher.email %></strong>.
  <%= link_to 'Edit profile', edit_teacher_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_teacher_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_teacher_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_teacher_session_path, :class => 'navbar-link'  %>
<% end %>
<%= link_to 'Create new Course', create_course_path, :class => 'navbar-link' %> |
<%= link_to 'View Course List', course_list_path, :class => 'navbar-link' %> |